# Default values for post.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
# nameOverride: post
replicaCount: 1
image:
  repository: dockerhub/post
  tag: latest
  pullPolicy: IfNotPresent

envVars:
  POST_DATABASE_HOST: mongodb
  POST_DATABASE_PORT: 27017

service:
  name: post
  type: ClusterIP
  externalPort: 5000
  internalPort: 5000

nodeSelector:
  cloud.google.com/gke-nodepool: default-pool

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi
